name: Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Unzip
        run: |
          mkdir -p temp_extract
          unzip doxygen_artifacts.zip -d temp_extract/
          mkdir -p public
          if [ -d "temp_extract/public" ]; then
            mv temp_extract/public/* public/
          else
            mv temp_extract/* public/
          fi
          rm -rf temp_extract

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
      - id: deployment
        uses: actions/deploy-pages@v4
